name: hugvi
base: core22
version: '1.4.0'
summary: A simple, local-first note-taking app
description: |
  Hugvi is a modern, privacy-focused, and fast desktop-only note-taking app. It is designed for developers to manage code snippets and notes with excellent syntax highlighting. All data is stored locally using SQLite, ensuring your notes remain private and secure. You can also export your notes as .md files or pure .txt files. Hugvi is available in English, French and German and supports Dark and Light modes out of the box.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  Hugvi:
    command: usr/bin/Hugvi
    desktop: usr/share/applications/Hugvi.desktop
    extensions: [ gnome ]
    environment:
      GDK_GL: disable

package-repositories:
  - type: apt
    components: [ main ]
    suites: [ noble ]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - xdg-utils
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      rustup toolchain install stable
      rustup default stable
      export PATH="$HOME/.cargo/bin:$PATH"
      npm install -g deno
      deno install
      deno run tauri build
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=Hugvi|Icon=/usr/share/icons/hicolor/32x32/apps/Hugvi.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/Hugvi.desktop